# Generated by Django 4.2.5 on 2023-09-28 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_atribuicao", models.DateTimeField()),
                ("valor", models.JSONField()),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task_manager.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=40, unique=True)),
                ("descricao", models.TextField()),
                ("concluida", models.BooleanField(default=False)),
                ("max_segundos_espera", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor", models.JSONField()),
                (
                    "parametro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultado",
                        to="task_manager.parametro",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parametro",
            name="resultado_associado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parametros",
                to="task_manager.resultado",
            ),
        ),
        migrations.AddField(
            model_name="parametro",
            name="tarefa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parametros",
                to="task_manager.tarefa",
            ),
        ),
    ]
