# Generated by Django 4.2.5 on 2023-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_alter_cliente_key_alter_parametro_data_atribuicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametro",
            name="resultado_associado",
        ),
        migrations.AlterField(
            model_name="resultado",
            name="valor",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
