# Generated by Django 4.2.5 on 2023-09-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_remove_parametro_resultado_associado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="configuracoes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
